CE103 Algorithms and Programming I HW4: ce103_hw4_cs_dll.ce103func Class Reference
ce103_hw4_cs_dll.ce103func Class Reference
Public Member Functions
int ce103_fibonacciNumber_cs (int fiIndex)
string ce103_strrev_cs (string fistr)
int ce103_strlen_cs (string fiStr)
string ce103_strcat_cs (string fiDest, string fiSrc)
int ce103_strcmp_cs (string fiLhs, string fiRhs)
string ce103_strcpy_cs (string fodest, string fisrc)
void ce103_hex2bin_cs (string fiHex, int fiHexLen, byte[] foBin)
void ce103_bin2hex_cs (byte[] fiBin, int fiBinLen, char[] foHex)
Member Function Documentation
ce103_bin2hex_cs()
void ce103_hw4_cs_dll.ce103func.ce103_bin2hex_cs (byte[] fiBin, int fiBinLen, char[] foHex) inline
Referenced by ce103_hw4_test.ce103_hw4_test.ce103_bin2hex_cs_test1(), ce103_hw4_test.ce103_hw4_test.ce103_bin2hex_cs_test2(), ce103_hw4_test.ce103_hw4_test.ce103_bin2hex_cs_test3(), ce103_hw4_test.ce103_hw4_test.ce103_bin2hex_cs_vs_cscs_test1(), ce103_hw4_test.ce103_hw4_test.ce103_bin2hex_cs_vs_cscs_test2(), and ce103_hw4_test.ce103_hw4_test.ce103_bin2hex_cs_vs_cscs_test3().
ce103_fibonacciNumber_cs()
int ce103_hw4_cs_dll.ce103func.ce103_fibonacciNumber_cs (int fiIndex) inline
Referenced by ce103_hw4_test.ce103_hw4_test.ce103_fibonacciNumber_cs_test1(), ce103_hw4_test.ce103_hw4_test.ce103_fibonacciNumber_cs_test2(), ce103_hw4_test.ce103_hw4_test.ce103_fibonacciNumber_cs_test3(), ce103_hw4_test.ce103_hw4_test.ce103_fibonacciNumber_cs_vs_cscs_test1(), ce103_hw4_test.ce103_hw4_test.ce103_fibonacciNumber_cs_vs_cscs_test2(), and ce103_hw4_test.ce103_hw4_test.ce103_fibonacciNumber_cs_vs_cscs_test3().
ce103_hex2bin_cs()
void ce103_hw4_cs_dll.ce103func.ce103_hex2bin_cs (string fiHex, int fiHexLen, byte[] foBin) inline
Referenced by ce103_hw4_test.ce103_hw4_test.ce103_hex2bin_cs_test1(), ce103_hw4_test.ce103_hw4_test.ce103_hex2bin_cs_test2(), ce103_hw4_test.ce103_hw4_test.ce103_hex2bin_cs_test3(), ce103_hw4_test.ce103_hw4_test.ce103_hex2bin_cs_vs_cscs_test1(), ce103_hw4_test.ce103_hw4_test.ce103_hex2bin_cs_vs_cscs_test2(), and ce103_hw4_test.ce103_hw4_test.ce103_hex2bin_cs_vs_cscs_test3().
ce103_strcat_cs()
string ce103_hw4_cs_dll.ce103func.ce103_strcat_cs (string fiDest, string fiSrc) inline
Referenced by ce103_hw4_test.ce103_hw4_test.ce103_strcat_cs_test1(), ce103_hw4_test.ce103_hw4_test.ce103_strcat_cs_test2(), ce103_hw4_test.ce103_hw4_test.ce103_strcat_cs_test3(), ce103_hw4_test.ce103_hw4_test.ce103_strcat_cs_vs_cscs_test1(), ce103_hw4_test.ce103_hw4_test.ce103_strcat_cs_vs_cscs_test2(), and ce103_hw4_test.ce103_hw4_test.ce103_strcat_cs_vs_cscs_test3().
ce103_strcmp_cs()
int ce103_hw4_cs_dll.ce103func.ce103_strcmp_cs (string fiLhs, string fiRhs) inline
Referenced by ce103_hw4_test.ce103_hw4_test.ce103_strcmp_cs_test1(), ce103_hw4_test.ce103_hw4_test.ce103_strcmp_cs_test2(), ce103_hw4_test.ce103_hw4_test.ce103_strcmp_cs_test3(), ce103_hw4_test.ce103_hw4_test.ce103_strcmp_cs_vs_cscs_test1(), ce103_hw4_test.ce103_hw4_test.ce103_strcmp_cs_vs_cscs_test2(), and ce103_hw4_test.ce103_hw4_test.ce103_strcmp_cs_vs_cscs_test3().
ce103_strcpy_cs()
string ce103_hw4_cs_dll.ce103func.ce103_strcpy_cs (string fodest, string fisrc) inline
Referenced by ce103_hw4_test.ce103_hw4_test.ce103_strcpy_cs_test1(), ce103_hw4_test.ce103_hw4_test.ce103_strcpy_cs_test2(), ce103_hw4_test.ce103_hw4_test.ce103_strcpy_cs_test3(), ce103_hw4_test.ce103_hw4_test.ce103_strcpy_cs_vs_cscs_test1(), ce103_hw4_test.ce103_hw4_test.ce103_strcpy_cs_vs_cscs_test2(), and ce103_hw4_test.ce103_hw4_test.ce103_strcpy_cs_vs_cscs_test3().
ce103_strlen_cs()
int ce103_hw4_cs_dll.ce103func.ce103_strlen_cs (string fiStr) inline
Referenced by ce103_hw4_test.ce103_hw4_test.ce103_strlen_cs_test1(), ce103_hw4_test.ce103_hw4_test.ce103_strlen_cs_test2(), ce103_hw4_test.ce103_hw4_test.ce103_strlen_cs_test3(), ce103_hw4_test.ce103_hw4_test.ce103_strlen_cs_vs_cscs_test1(), ce103_hw4_test.ce103_hw4_test.ce103_strlen_cs_vs_cscs_test2(), and ce103_hw4_test.ce103_hw4_test.ce103_strlen_cs_vs_cscs_test3().
ce103_strrev_cs()
string ce103_hw4_cs_dll.ce103func.ce103_strrev_cs (string fistr) inline
Referenced by ce103_hw4_test.ce103_hw4_test.ce103_strrev_cs_test1(), ce103_hw4_test.ce103_hw4_test.ce103_strrev_cs_test2(), ce103_hw4_test.ce103_hw4_test.ce103_strrev_cs_test3(), ce103_hw4_test.ce103_hw4_test.ce103_strrev_cs_vs_cscs_test1(), ce103_hw4_test.ce103_hw4_test.ce103_strrev_cs_vs_cscs_test2(), and ce103_hw4_test.ce103_hw4_test.ce103_strrev_cs_vs_cscs_test3().
The documentation for this class was generated from the following file:
C:/hm4/ce103-hw4-omer-polat/ce103-hw4-cs-dll/Class1.cs