CE103 Algorithms and Programming I HW4: ce103_hw4_cs_dll.ce103CsFunctions Class Reference
ce103_hw4_cs_dll.ce103CsFunctions Class Reference
Public Member Functions
static int ce103_fibonacciNumber_cpp (int fiIndex)
static string ce103_strrev_cpp (string fiStr)
static int ce103_strlen_cpp (string fiStr)
static string ce103_strcat_cpp (string fiDest, string fiSrc)
static int ce103_strcmp_cpp (string fiLhs, string fiRhs)
static string ce103_strcpy_cpp (string foDestination, string fiSource)
static void ce103_hex2bin_cpp (string fiHex, int fiHexLen, byte[] foBin)
static void ce103_bin2hex_cpp (byte[] fiBin, int fiBinLen, StringBuilder foHex)
int ce103_fibonacciNumber_cs_cs (int fiIndex)
string ce103_strrev_cs_cs (string fiStr)
int ce103_strlen_cs_cs (string fiStr)
string ce103_strcat_cs_cs (string fiDest, string fiSrc)
int ce103_strcmp_cs_cs (string fiDest, string fiSrc)
string ce103_strcpy_cs_cs (string foDestination, string fiSource)
void ce103_hex2bin_cs_cs (string fiHex, int fiHexLen, byte[] foBin)
void ce103_bin2hex_cs_cs (byte[] fiBin, int fiBinLen, StringBuilder foHex)
Member Function Documentation
ce103_bin2hex_cpp()
static void ce103_hw4_cs_dll.ce103CsFunctions.ce103_bin2hex_cpp (byte[] fiBin, int fiBinLen, StringBuilder foHex)
Referenced by ce103_hw4_cs_dll.ce103CsFunctions.ce103_bin2hex_cs_cs().
ce103_bin2hex_cs_cs()
void ce103_hw4_cs_dll.ce103CsFunctions.ce103_bin2hex_cs_cs (byte[] fiBin, int fiBinLen, StringBuilder foHex) inline
References ce103_hw4_cs_dll.ce103CsFunctions.ce103_bin2hex_cpp().
Referenced by ce103_hw4_test.ce103_hw4_test.ce103_bin2hex_cs_cs_test1(), ce103_hw4_test.ce103_hw4_test.ce103_bin2hex_cs_cs_test2(), ce103_hw4_test.ce103_hw4_test.ce103_bin2hex_cs_cs_test3(), ce103_hw4_test.ce103_hw4_test.ce103_bin2hex_cs_vs_cscs_test1(), ce103_hw4_test.ce103_hw4_test.ce103_bin2hex_cs_vs_cscs_test2(), and ce103_hw4_test.ce103_hw4_test.ce103_bin2hex_cs_vs_cscs_test3().
ce103_fibonacciNumber_cpp()
static int ce103_hw4_cs_dll.ce103CsFunctions.ce103_fibonacciNumber_cpp (int fiIndex)
Referenced by ce103_hw4_cs_dll.ce103CsFunctions.ce103_fibonacciNumber_cs_cs().
ce103_fibonacciNumber_cs_cs()
int ce103_hw4_cs_dll.ce103CsFunctions.ce103_fibonacciNumber_cs_cs (int fiIndex) inline
References ce103_hw4_cs_dll.ce103CsFunctions.ce103_fibonacciNumber_cpp().
Referenced by ce103_hw4_test.ce103_hw4_test.ce103_fibonacciNumber_cs_cs_test1(), ce103_hw4_test.ce103_hw4_test.ce103_fibonacciNumber_cs_cs_test2(), ce103_hw4_test.ce103_hw4_test.ce103_fibonacciNumber_cs_cs_test3(), ce103_hw4_test.ce103_hw4_test.ce103_fibonacciNumber_cs_vs_cscs_test1(), ce103_hw4_test.ce103_hw4_test.ce103_fibonacciNumber_cs_vs_cscs_test2(), and ce103_hw4_test.ce103_hw4_test.ce103_fibonacciNumber_cs_vs_cscs_test3().
ce103_hex2bin_cpp()
static void ce103_hw4_cs_dll.ce103CsFunctions.ce103_hex2bin_cpp (string fiHex, int fiHexLen, byte[] foBin)
Referenced by ce103_hw4_cs_dll.ce103CsFunctions.ce103_hex2bin_cs_cs().
ce103_hex2bin_cs_cs()
void ce103_hw4_cs_dll.ce103CsFunctions.ce103_hex2bin_cs_cs (string fiHex, int fiHexLen, byte[] foBin) inline
References ce103_hw4_cs_dll.ce103CsFunctions.ce103_hex2bin_cpp().
Referenced by ce103_hw4_test.ce103_hw4_test.ce103_hex2bin_cs_cs_test1(), ce103_hw4_test.ce103_hw4_test.ce103_hex2bin_cs_cs_test2(), ce103_hw4_test.ce103_hw4_test.ce103_hex2bin_cs_cs_test3(), ce103_hw4_test.ce103_hw4_test.ce103_hex2bin_cs_vs_cscs_test1(), ce103_hw4_test.ce103_hw4_test.ce103_hex2bin_cs_vs_cscs_test2(), and ce103_hw4_test.ce103_hw4_test.ce103_hex2bin_cs_vs_cscs_test3().
ce103_strcat_cpp()
static string ce103_hw4_cs_dll.ce103CsFunctions.ce103_strcat_cpp (string fiDest, string fiSrc)
Referenced by ce103_hw4_cs_dll.ce103CsFunctions.ce103_strcat_cs_cs().
ce103_strcat_cs_cs()
string ce103_hw4_cs_dll.ce103CsFunctions.ce103_strcat_cs_cs (string fiDest, string fiSrc) inline
References ce103_hw4_cs_dll.ce103CsFunctions.ce103_strcat_cpp().
Referenced by ce103_hw4_test.ce103_hw4_test.ce103_strcat_cs_cs_test1(), ce103_hw4_test.ce103_hw4_test.ce103_strcat_cs_cs_test2(), ce103_hw4_test.ce103_hw4_test.ce103_strcat_cs_cs_test3(), ce103_hw4_test.ce103_hw4_test.ce103_strcat_cs_vs_cscs_test1(), ce103_hw4_test.ce103_hw4_test.ce103_strcat_cs_vs_cscs_test2(), and ce103_hw4_test.ce103_hw4_test.ce103_strcat_cs_vs_cscs_test3().
ce103_strcmp_cpp()
static int ce103_hw4_cs_dll.ce103CsFunctions.ce103_strcmp_cpp (string fiLhs, string fiRhs)
Referenced by ce103_hw4_cs_dll.ce103CsFunctions.ce103_strcmp_cs_cs().
ce103_strcmp_cs_cs()
int ce103_hw4_cs_dll.ce103CsFunctions.ce103_strcmp_cs_cs (string fiDest, string fiSrc) inline
References ce103_hw4_cs_dll.ce103CsFunctions.ce103_strcmp_cpp().
Referenced by ce103_hw4_test.ce103_hw4_test.ce103_strcmp_cs_cs_test1(), ce103_hw4_test.ce103_hw4_test.ce103_strcmp_cs_cs_test2(), ce103_hw4_test.ce103_hw4_test.ce103_strcmp_cs_cs_test3(), ce103_hw4_test.ce103_hw4_test.ce103_strcmp_cs_vs_cscs_test1(), ce103_hw4_test.ce103_hw4_test.ce103_strcmp_cs_vs_cscs_test2(), and ce103_hw4_test.ce103_hw4_test.ce103_strcmp_cs_vs_cscs_test3().
ce103_strcpy_cpp()
static string ce103_hw4_cs_dll.ce103CsFunctions.ce103_strcpy_cpp (string foDestination, string fiSource)
Referenced by ce103_hw4_cs_dll.ce103CsFunctions.ce103_strcpy_cs_cs().
ce103_strcpy_cs_cs()
string ce103_hw4_cs_dll.ce103CsFunctions.ce103_strcpy_cs_cs (string foDestination, string fiSource) inline
References ce103_hw4_cs_dll.ce103CsFunctions.ce103_strcpy_cpp().
Referenced by ce103_hw4_test.ce103_hw4_test.ce103_strcpy_cs_cs_test1(), ce103_hw4_test.ce103_hw4_test.ce103_strcpy_cs_cs_test2(), ce103_hw4_test.ce103_hw4_test.ce103_strcpy_cs_cs_test3(), ce103_hw4_test.ce103_hw4_test.ce103_strcpy_cs_vs_cscs_test1(), ce103_hw4_test.ce103_hw4_test.ce103_strcpy_cs_vs_cscs_test2(), and ce103_hw4_test.ce103_hw4_test.ce103_strcpy_cs_vs_cscs_test3().
ce103_strlen_cpp()
static int ce103_hw4_cs_dll.ce103CsFunctions.ce103_strlen_cpp (string fiStr)
Referenced by ce103_hw4_cs_dll.ce103CsFunctions.ce103_strlen_cs_cs().
ce103_strlen_cs_cs()
int ce103_hw4_cs_dll.ce103CsFunctions.ce103_strlen_cs_cs (string fiStr) inline
References ce103_hw4_cs_dll.ce103CsFunctions.ce103_strlen_cpp().
Referenced by ce103_hw4_test.ce103_hw4_test.ce103_strlen_cs_cs_test1(), ce103_hw4_test.ce103_hw4_test.ce103_strlen_cs_cs_test2(), ce103_hw4_test.ce103_hw4_test.ce103_strlen_cs_cs_test3(), ce103_hw4_test.ce103_hw4_test.ce103_strlen_cs_vs_cscs_test1(), ce103_hw4_test.ce103_hw4_test.ce103_strlen_cs_vs_cscs_test2(), and ce103_hw4_test.ce103_hw4_test.ce103_strlen_cs_vs_cscs_test3().
ce103_strrev_cpp()
static string ce103_hw4_cs_dll.ce103CsFunctions.ce103_strrev_cpp (string fiStr)
Referenced by ce103_hw4_cs_dll.ce103CsFunctions.ce103_strrev_cs_cs().
ce103_strrev_cs_cs()
string ce103_hw4_cs_dll.ce103CsFunctions.ce103_strrev_cs_cs (string fiStr) inline
References ce103_hw4_cs_dll.ce103CsFunctions.ce103_strrev_cpp().
Referenced by ce103_hw4_test.ce103_hw4_test.ce103_strrev_cs_cs_test1(), ce103_hw4_test.ce103_hw4_test.ce103_strrev_cs_cs_test2(), ce103_hw4_test.ce103_hw4_test.ce103_strrev_cs_cs_test3(), ce103_hw4_test.ce103_hw4_test.ce103_strrev_cs_vs_cscs_test1(), ce103_hw4_test.ce103_hw4_test.ce103_strrev_cs_vs_cscs_test2(), and ce103_hw4_test.ce103_hw4_test.ce103_strrev_cs_vs_cscs_test3().
The documentation for this class was generated from the following file:
C:/hm4/ce103-hw4-omer-polat/ce103-hw4-cs-dll/Class2.cs